# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SearchImageApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
	platform :ios, '8.0'
  # Pods for SearchImageApp
	pod 'AFNetworking', '~> 3.0'
	pod 'SDWebImage', '~> 4.0'
	pod 'MBProgressHUD', '~> 1.0.0'
    pod 'JSONModel'
end
